### ISSUE TITLE
How to run examples locally?

### ISSUE THREAD

**Issue by ajusa** [treeform/nimtemplate#6]
I see that the test directory includes a config.nims that tells the compiler to use the src directory for looking up packages, is there a reason that the examples directory doesn't have the same configuration? Am I supposed to use a nimble command to run examples, or nimble install before running examples?

Curious as to what your workflow is when developing packages.

**Comment by guzba** [comment]
I guess to start answering I would say, typically we run examples from the repo root. So If i made a new project from this template, like Mummy for example, then I would cd to /path/to/mummy and have that as my working directory. From there I `nimble develop` after having the .nimble file updated and ready.

Running tests is either `nimble test` or `nim c -r tests/test.nim` and the same for examples, `nim c -r examples/example.nim`

I think the ../src config.nims is there so the tests look at src/ even if nimble develop hasn't been run? I'm not exactly sure on that. Does this help?

**Comment by ajusa** [comment]
It does, yes! `nimble develop` is the main bit of information I was missing, and the config.nims existing for tests was throwing me off. Thanks for the information!
